# 应用信息
appinfo:
    # 小程序名称
    name: 海淘助手小六
    # 版本号
    version: 1.2.1
    # 微服务开启的端口号
    port: 12333
    # 联系方式
    contact: anlasheng@gmail.com By Julian

# 微信应用的信息
weixin:
    # 第三方用户唯一凭证
    appid: 
    # 第三方用户唯一凭证密钥，即appsecret
    secret: 
    granttype: client_credential
    # 小程序商品详细页的路径
    path: 
    # 获取access_token 请求地址 GET
    tokenurl: https://api.weixin.qq.com/cgi-bin/token
    # 获取小程序页面二维码地址 POST
    createurl: https://api.weixin.qq.com/cgi-bin/wxaapp/createwxaqrcode?access_token=

# 百度短链接
baidu:
    # 创建短链接地址
    createurl: http://dwz.cn/create.php

# 关于
about:
- name: Julian
  email: anlasheng@gmail.com